title: Mandar Shringari  # Your name



description: I am a dedicated student at Ditton Park Academy, currently pursuing my GCSEs with a strong focus on STEM subjects. I have developed skills in Python programming, robotics, and CAD design, and have hands-on experience from internships and competitions in engineering and technology.


theme: jekyll-theme-minimal

plugins:
  - jekyll-seo # Add SEO plugin

email: mandar.v.shringari@gmail.com  44 Hurworth Avenue,  Slough SL3 7FE  mandar.v.shringari@gmail.com  07438355713  
