title: Mandar Shringari
email: mandar.v.shringari@gmail.com
description: >
  I am a dedicated student at Ditton Park Academy, focusing on STEM subjects.
  Proficient in Python programming, robotics, and CAD design with practical
  experience from internships and engineering competitions.
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo


