title: Mandar Shringari  # Your name

logo: 1.png # Use a relative path to logo image

description: Data science and AI in agriculture – where bytes and botany blend for a better world. # Fix hyphenation

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal

plugins:
  - jekyll-seo # Add SEO plugin

email: mandar.v.shringari@gmail.com # Allow visitors to contact you
